import type { QuizConfig, SubmittedAnswer } from '@world-quiz/quiz/domain';
import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

const timestampMs = (name: string) =>
  timestamp(name, { withTimezone: true, mode: 'date', precision: 3 });

/**
 * A player. Created on the first sign-in with a provider; everything the
 * player owns is deleted with this row (account deletion).
 */
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  displayName: text('display_name'),
  /** As shared by the provider; informational, never used to link accounts. */
  email: text('email'),
  /**
   * The public name on leaderboards, chosen by the player. `null` until then:
   * a default ("Player 4821") is derived from the id, so the provider's name
   * is never published without the player choosing it.
   */
  nickname: text('nickname'),
  createdAt: timestampMs('created_at').notNull().defaultNow(),
});

/**
 * How a user signs in: one row per provider account. The provider's stable
 * subject (`sub`) identifies the account; e-mail addresses are not used for
 * that, because they can change and Apple may hide them behind a relay.
 */
export const userIdentities = pgTable(
  'user_identities',
  {
    provider: text('provider').notNull(),
    subject: text('subject').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    email: text('email'),
    createdAt: timestampMs('created_at').notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.provider, table.subject] }),
    index('user_identities_user_idx').on(table.userId),
  ],
);

/**
 * Refresh tokens, stored as SHA-256 hashes only: a database leak does not
 * leak usable tokens.
 *
 * Tokens rotate: each refresh marks the presented token as used and issues a
 * new one in the same family. A used or revoked token presented again means
 * it was copied, so the whole family is revoked (reuse detection).
 */
export const refreshTokens = pgTable(
  'refresh_tokens',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** All tokens descending from one sign-in. */
    familyId: uuid('family_id').notNull(),
    tokenHash: text('token_hash').notNull().unique(),
    createdAt: timestampMs('created_at').notNull(),
    expiresAt: timestampMs('expires_at').notNull(),
    /** Set when the token was exchanged for a new one. */
    usedAt: timestampMs('used_at'),
    /** Set when the family was revoked (sign-out, reuse detected). */
    revokedAt: timestampMs('revoked_at'),
  },
  (table) => [
    index('refresh_tokens_family_idx').on(table.familyId),
    index('refresh_tokens_user_idx').on(table.userId),
  ],
);

/**
 * One finished quiz session, as graded by the server.
 *
 * Every derived number (answered, correct, duration, perfect) comes from the
 * server's replay of the session, never from the client. The columns that are
 * part of the replay input (`config`, `seed`, timestamps) are stored exactly,
 * so a session can be replayed again later (for example to rebuild progress).
 */
export const quizSessions = pgTable(
  'quiz_sessions',
  {
    /** Generated by the client once per session: the idempotency key. */
    id: uuid('id').primaryKey(),
    /** Owner. Sessions are recorded for signed-in players only. */
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    category: text('category').notNull(),
    difficulty: text('difficulty').notNull(),
    mode: text('mode').notNull(),
    scope: text('scope').notNull(),
    /** The exact configuration that was replayed. */
    config: jsonb('config').$type<QuizConfig>().notNull(),
    seed: text('seed').notNull(),
    startedAt: timestampMs('started_at').notNull(),
    finishedAt: timestampMs('finished_at').notNull(),
    endReason: text('end_reason').notNull(),
    answered: integer('answered').notNull(),
    correct: integer('correct').notNull(),
    durationMs: integer('duration_ms').notNull(),
    completed: boolean('completed').notNull(),
    perfect: boolean('perfect').notNull(),
    /**
     * SHA-256 of the canonical request. A retry with the same id must carry
     * the same session; a different body under the same id is a conflict.
     */
    requestHash: text('request_hash').notNull(),
    recordedAt: timestampMs('recorded_at').notNull().defaultNow(),
  },
  (table) => [
    index('quiz_sessions_user_recorded_idx').on(table.userId, table.recordedAt),
    check(
      'quiz_sessions_correct_le_answered',
      sql`${table.correct} <= ${table.answered}`,
    ),
    check('quiz_sessions_duration_non_negative', sql`${table.durationMs} >= 0`),
  ],
);

/** The answers of a session, in the order they were given. */
export const quizAnswers = pgTable(
  'quiz_answers',
  {
    sessionId: uuid('session_id')
      .notNull()
      .references(() => quizSessions.id, { onDelete: 'cascade' }),
    sequence: integer('sequence').notNull(),
    /** The country the question was about. */
    countryCode: text('country_code').notNull(),
    /** What the player submitted: a choice or typed text. */
    answer: jsonb('answer').$type<SubmittedAnswer>().notNull(),
    correct: boolean('correct').notNull(),
    /** `choice`, `exact`, `typo` or `incorrect`, as judged by the server. */
    judgement: text('judgement').notNull(),
    answeredAt: timestampMs('answered_at').notNull(),
  },
  (table) => [primaryKey({ columns: [table.sessionId, table.sequence] })],
);

/**
 * Leaderboard challenges: issued by the server with its own seed, played once.
 *
 * When the session that plays a challenge is recorded, the row gets that
 * session and the server's verdict: `outcome` is `ranked` or the reason it is
 * not, and `completion_ms` / `recorded_at` are the ranking keys. Rankings are
 * queries over the ranked rows (docs/domain/leaderboard.md).
 */
export const challenges = pgTable(
  'challenges',
  {
    id: uuid('id').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** `capitals-easy`, `capitals-hard`, `flags-easy` or `flags-hard`. */
    board: text('board').notNull(),
    seed: text('seed').notNull(),
    issuedAt: timestampMs('issued_at').notNull(),
    /** The session that played it; `null` while unplayed. */
    sessionId: uuid('session_id')
      .unique()
      .references(() => quizSessions.id, { onDelete: 'cascade' }),
    /** `ranked`, or why the run is not ranked. */
    outcome: text('outcome'),
    /** The run's completion time, as measured by the client and checked. */
    completionMs: integer('completion_ms'),
    /** When the server accepted the run: the first tie-break. */
    recordedAt: timestampMs('recorded_at'),
    /** Whether the run beat the player's previous best on the board. */
    personalRecord: boolean('personal_record'),
  },
  (table) => [
    index('challenges_user_idx').on(table.userId),
    // The ranking order, over ranked runs only.
    index('challenges_ranking_idx')
      .on(table.board, table.completionMs, table.recordedAt, table.sessionId)
      .where(sql`${table.outcome} = 'ranked'`),
  ],
);

export const schema = {
  users,
  userIdentities,
  refreshTokens,
  quizSessions,
  quizAnswers,
  challenges,
};
export type Schema = typeof schema;
