import type { QuizConfig, SubmittedAnswer } from '@world-quiz/quiz/domain';
import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

const timestampMs = (name: string) =>
  timestamp(name, { withTimezone: true, mode: 'date', precision: 3 });

/**
 * One finished quiz session, as graded by the server.
 *
 * Every derived number (answered, correct, duration, perfect) comes from the
 * server's replay of the session, never from the client. The columns that are
 * part of the replay input (`config`, `seed`, timestamps) are stored exactly,
 * so a session can be replayed again later (for example to rebuild progress).
 */
export const quizSessions = pgTable(
  'quiz_sessions',
  {
    /** Generated by the client once per session: the idempotency key. */
    id: uuid('id').primaryKey(),
    /** Owner. Null until sign-in exists (Phase 7). */
    userId: uuid('user_id'),
    category: text('category').notNull(),
    difficulty: text('difficulty').notNull(),
    mode: text('mode').notNull(),
    scope: text('scope').notNull(),
    /** The exact configuration that was replayed. */
    config: jsonb('config').$type<QuizConfig>().notNull(),
    seed: text('seed').notNull(),
    startedAt: timestampMs('started_at').notNull(),
    finishedAt: timestampMs('finished_at').notNull(),
    endReason: text('end_reason').notNull(),
    answered: integer('answered').notNull(),
    correct: integer('correct').notNull(),
    durationMs: integer('duration_ms').notNull(),
    completed: boolean('completed').notNull(),
    perfect: boolean('perfect').notNull(),
    /**
     * SHA-256 of the canonical request. A retry with the same id must carry
     * the same session; a different body under the same id is a conflict.
     */
    requestHash: text('request_hash').notNull(),
    recordedAt: timestampMs('recorded_at').notNull().defaultNow(),
  },
  (table) => [
    index('quiz_sessions_user_recorded_idx').on(table.userId, table.recordedAt),
    check(
      'quiz_sessions_correct_le_answered',
      sql`${table.correct} <= ${table.answered}`,
    ),
    check('quiz_sessions_duration_non_negative', sql`${table.durationMs} >= 0`),
  ],
);

/** The answers of a session, in the order they were given. */
export const quizAnswers = pgTable(
  'quiz_answers',
  {
    sessionId: uuid('session_id')
      .notNull()
      .references(() => quizSessions.id, { onDelete: 'cascade' }),
    sequence: integer('sequence').notNull(),
    /** The country the question was about. */
    countryCode: text('country_code').notNull(),
    /** What the player submitted: a choice or typed text. */
    answer: jsonb('answer').$type<SubmittedAnswer>().notNull(),
    correct: boolean('correct').notNull(),
    /** `choice`, `exact`, `typo` or `incorrect`, as judged by the server. */
    judgement: text('judgement').notNull(),
    answeredAt: timestampMs('answered_at').notNull(),
  },
  (table) => [primaryKey({ columns: [table.sessionId, table.sequence] })],
);

export const schema = { quizSessions, quizAnswers };
export type Schema = typeof schema;
