import type { CountryDataset } from '@world-quiz/quiz/domain';

/**
 * The World Quiz country dataset: 193 UN member states + 2 UN observer states
 * (Vatican City, Palestine) = 195 countries. Sorted by English name.
 *
 * Maintained by hand. See docs/domain/countries.md for scope, sources
 * (Wikidata, CC0; UN M49 regions), naming rules, known ambiguities and the
 * update procedure (`nx run quiz-countries:check-wikidata`).
 *
 * `name`/`capital` are displayed; `*Aliases` are only accepted in Hard mode.
 */
export const COUNTRIES: CountryDataset = [
  {
    code: 'af',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Afghanistan', ru: 'Афганистан' },
    capital: { en: 'Kabul', ru: 'Кабул' },
  },
  {
    code: 'al',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Albania', ru: 'Албания' },
    capital: { en: 'Tirana', ru: 'Тирана' },
  },
  {
    code: 'dz',
    region: 'africa',
    subregion: 'northern-africa',
    name: { en: 'Algeria', ru: 'Алжир' },
    capital: { en: 'Algiers', ru: 'Алжир' },
  },
  {
    code: 'ad',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Andorra', ru: 'Андорра' },
    capital: { en: 'Andorra la Vella', ru: 'Андорра-ла-Велья' },
  },
  {
    code: 'ao',
    region: 'africa',
    subregion: 'middle-africa',
    name: { en: 'Angola', ru: 'Ангола' },
    capital: { en: 'Luanda', ru: 'Луанда' },
  },
  {
    code: 'ag',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Antigua and Barbuda', ru: 'Антигуа и Барбуда' },
    capital: { en: "St. John's", ru: 'Сент-Джонс' },
  },
  {
    code: 'ar',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Argentina', ru: 'Аргентина' },
    capital: { en: 'Buenos Aires', ru: 'Буэнос-Айрес' },
  },
  {
    code: 'am',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Armenia', ru: 'Армения' },
    capital: { en: 'Yerevan', ru: 'Ереван' },
  },
  {
    code: 'au',
    region: 'oceania',
    subregion: 'australia-and-new-zealand',
    name: { en: 'Australia', ru: 'Австралия' },
    capital: { en: 'Canberra', ru: 'Канберра' },
  },
  {
    code: 'at',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Austria', ru: 'Австрия' },
    capital: { en: 'Vienna', ru: 'Вена' },
  },
  {
    code: 'az',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Azerbaijan', ru: 'Азербайджан' },
    capital: { en: 'Baku', ru: 'Баку' },
  },
  {
    code: 'bs',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Bahamas', ru: 'Багамские Острова' },
    nameAliases: { ru: ['Багамы'] },
    capital: { en: 'Nassau', ru: 'Нассау' },
  },
  {
    code: 'bh',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Bahrain', ru: 'Бахрейн' },
    capital: { en: 'Manama', ru: 'Манама' },
  },
  {
    code: 'bd',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Bangladesh', ru: 'Бангладеш' },
    capital: { en: 'Dhaka', ru: 'Дакка' },
  },
  {
    code: 'bb',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Barbados', ru: 'Барбадос' },
    capital: { en: 'Bridgetown', ru: 'Бриджтаун' },
  },
  {
    code: 'by',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Belarus', ru: 'Беларусь' },
    nameAliases: { ru: ['Белоруссия'] },
    capital: { en: 'Minsk', ru: 'Минск' },
  },
  {
    code: 'be',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Belgium', ru: 'Бельгия' },
    capital: { en: 'Brussels', ru: 'Брюссель' },
  },
  {
    code: 'bz',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'Belize', ru: 'Белиз' },
    capital: { en: 'Belmopan', ru: 'Бельмопан' },
  },
  // Porto-Novo is the constitutional capital; Cotonou is the seat of government.
  {
    code: 'bj',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Benin', ru: 'Бенин' },
    capital: { en: 'Porto-Novo', ru: 'Порто-Ново' },
    capitalAliases: { en: ['Cotonou'], ru: ['Котону'] },
  },
  {
    code: 'bt',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Bhutan', ru: 'Бутан' },
    capital: { en: 'Thimphu', ru: 'Тхимпху' },
  },
  // Sucre is the constitutional capital; La Paz is the seat of government.
  {
    code: 'bo',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Bolivia', ru: 'Боливия' },
    capital: { en: 'Sucre', ru: 'Сукре' },
    capitalAliases: { en: ['La Paz'], ru: ['Ла-Пас'] },
  },
  {
    code: 'ba',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Bosnia and Herzegovina', ru: 'Босния и Герцеговина' },
    capital: { en: 'Sarajevo', ru: 'Сараево' },
  },
  {
    code: 'bw',
    region: 'africa',
    subregion: 'southern-africa',
    name: { en: 'Botswana', ru: 'Ботсвана' },
    capital: { en: 'Gaborone', ru: 'Габороне' },
  },
  {
    code: 'br',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Brazil', ru: 'Бразилия' },
    capital: { en: 'Brasília', ru: 'Бразилиа' },
  },
  {
    code: 'bn',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Brunei', ru: 'Бруней' },
    nameAliases: { en: ['Brunei Darussalam'] },
    capital: { en: 'Bandar Seri Begawan', ru: 'Бандар-Сери-Бегаван' },
  },
  {
    code: 'bg',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Bulgaria', ru: 'Болгария' },
    capital: { en: 'Sofia', ru: 'София' },
  },
  {
    code: 'bf',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Burkina Faso', ru: 'Буркина-Фасо' },
    capital: { en: 'Ouagadougou', ru: 'Уагадугу' },
  },
  // Gitega has been the political capital since 2019; Bujumbura remains the economic capital.
  {
    code: 'bi',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Burundi', ru: 'Бурунди' },
    capital: { en: 'Gitega', ru: 'Гитега' },
    capitalAliases: { en: ['Bujumbura'], ru: ['Бужумбура'] },
  },
  {
    code: 'cv',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Cabo Verde', ru: 'Кабо-Верде' },
    nameAliases: { en: ['Cape Verde'], ru: ['Острова Зелёного Мыса'] },
    capital: { en: 'Praia', ru: 'Прая' },
  },
  {
    code: 'kh',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Cambodia', ru: 'Камбоджа' },
    capital: { en: 'Phnom Penh', ru: 'Пномпень' },
  },
  {
    code: 'cm',
    region: 'africa',
    subregion: 'middle-africa',
    name: { en: 'Cameroon', ru: 'Камерун' },
    capital: { en: 'Yaoundé', ru: 'Яунде' },
  },
  {
    code: 'ca',
    region: 'north-america',
    subregion: 'northern-america',
    name: { en: 'Canada', ru: 'Канада' },
    capital: { en: 'Ottawa', ru: 'Оттава' },
  },
  {
    code: 'cf',
    region: 'africa',
    subregion: 'middle-africa',
    name: {
      en: 'Central African Republic',
      ru: 'Центральноафриканская Республика',
    },
    nameAliases: { en: ['CAR'], ru: ['ЦАР'] },
    capital: { en: 'Bangui', ru: 'Банги' },
  },
  {
    code: 'td',
    region: 'africa',
    subregion: 'middle-africa',
    name: { en: 'Chad', ru: 'Чад' },
    capital: { en: "N'Djamena", ru: 'Нджамена' },
  },
  {
    code: 'cl',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Chile', ru: 'Чили' },
    capital: { en: 'Santiago', ru: 'Сантьяго' },
  },
  {
    code: 'cn',
    region: 'asia',
    subregion: 'eastern-asia',
    name: { en: 'China', ru: 'Китай' },
    nameAliases: { en: ["People's Republic of China"], ru: ['КНР'] },
    capital: { en: 'Beijing', ru: 'Пекин' },
  },
  {
    code: 'co',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Colombia', ru: 'Колумбия' },
    capital: { en: 'Bogotá', ru: 'Богота' },
  },
  {
    code: 'km',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Comoros', ru: 'Коморы' },
    capital: { en: 'Moroni', ru: 'Морони' },
  },
  {
    code: 'cr',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'Costa Rica', ru: 'Коста-Рика' },
    capital: { en: 'San José', ru: 'Сан-Хосе' },
  },
  // Yamoussoukro is the official capital; Abidjan is the economic centre and hosts most institutions.
  {
    code: 'ci',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: "Côte d'Ivoire", ru: 'Кот-д’Ивуар' },
    nameAliases: { en: ['Ivory Coast'], ru: ['Берег Слоновой Кости'] },
    capital: { en: 'Yamoussoukro', ru: 'Ямусукро' },
    capitalAliases: { en: ['Abidjan'], ru: ['Абиджан'] },
  },
  {
    code: 'hr',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Croatia', ru: 'Хорватия' },
    capital: { en: 'Zagreb', ru: 'Загреб' },
  },
  {
    code: 'cu',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Cuba', ru: 'Куба' },
    capital: { en: 'Havana', ru: 'Гавана' },
  },
  {
    code: 'cy',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Cyprus', ru: 'Кипр' },
    capital: { en: 'Nicosia', ru: 'Никосия' },
  },
  {
    code: 'cz',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Czechia', ru: 'Чехия' },
    nameAliases: { en: ['Czech Republic'], ru: ['Чешская Республика'] },
    capital: { en: 'Prague', ru: 'Прага' },
  },
  {
    code: 'cd',
    region: 'africa',
    subregion: 'middle-africa',
    name: {
      en: 'Democratic Republic of the Congo',
      ru: 'Демократическая Республика Конго',
    },
    nameAliases: {
      en: ['DR Congo', 'DRC', 'Congo-Kinshasa'],
      ru: ['ДР Конго', 'ДРК', 'Конго-Киншаса'],
    },
    capital: { en: 'Kinshasa', ru: 'Киншаса' },
  },
  {
    code: 'dk',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Denmark', ru: 'Дания' },
    capital: { en: 'Copenhagen', ru: 'Копенгаген' },
  },
  {
    code: 'dj',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Djibouti', ru: 'Джибути' },
    capital: { en: 'Djibouti', ru: 'Джибути' },
  },
  {
    code: 'dm',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Dominica', ru: 'Доминика' },
    capital: { en: 'Roseau', ru: 'Розо' },
  },
  {
    code: 'do',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Dominican Republic', ru: 'Доминиканская Республика' },
    capital: { en: 'Santo Domingo', ru: 'Санто-Доминго' },
  },
  {
    code: 'ec',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Ecuador', ru: 'Эквадор' },
    capital: { en: 'Quito', ru: 'Кито' },
  },
  {
    code: 'eg',
    region: 'africa',
    subregion: 'northern-africa',
    name: { en: 'Egypt', ru: 'Египет' },
    capital: { en: 'Cairo', ru: 'Каир' },
  },
  {
    code: 'sv',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'El Salvador', ru: 'Сальвадор' },
    capital: { en: 'San Salvador', ru: 'Сан-Сальвадор' },
  },
  // Ciudad de la Paz was designated as the future capital; Malabo remains the functioning capital.
  {
    code: 'gq',
    region: 'africa',
    subregion: 'middle-africa',
    name: { en: 'Equatorial Guinea', ru: 'Экваториальная Гвинея' },
    capital: { en: 'Malabo', ru: 'Малабо' },
    capitalAliases: { en: ['Ciudad de la Paz'], ru: ['Сьюдад-де-ла-Пас'] },
  },
  {
    code: 'er',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Eritrea', ru: 'Эритрея' },
    capital: { en: 'Asmara', ru: 'Асмэра' },
    capitalAliases: { ru: ['Асмара'] },
  },
  {
    code: 'ee',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Estonia', ru: 'Эстония' },
    capital: { en: 'Tallinn', ru: 'Таллин' },
    capitalAliases: { ru: ['Таллинн'] },
  },
  // Mbabane is the executive capital; Lobamba is the legislative and royal capital.
  {
    code: 'sz',
    region: 'africa',
    subregion: 'southern-africa',
    name: { en: 'Eswatini', ru: 'Эсватини' },
    nameAliases: { en: ['Swaziland'], ru: ['Свазиленд'] },
    capital: { en: 'Mbabane', ru: 'Мбабане' },
    capitalAliases: { en: ['Lobamba'], ru: ['Лобамба'] },
  },
  {
    code: 'et',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Ethiopia', ru: 'Эфиопия' },
    capital: { en: 'Addis Ababa', ru: 'Аддис-Абеба' },
  },
  {
    code: 'fj',
    region: 'oceania',
    subregion: 'melanesia',
    name: { en: 'Fiji', ru: 'Фиджи' },
    capital: { en: 'Suva', ru: 'Сува' },
  },
  {
    code: 'fi',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Finland', ru: 'Финляндия' },
    capital: { en: 'Helsinki', ru: 'Хельсинки' },
  },
  {
    code: 'fr',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'France', ru: 'Франция' },
    capital: { en: 'Paris', ru: 'Париж' },
  },
  {
    code: 'ga',
    region: 'africa',
    subregion: 'middle-africa',
    name: { en: 'Gabon', ru: 'Габон' },
    capital: { en: 'Libreville', ru: 'Либревиль' },
  },
  {
    code: 'gm',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Gambia', ru: 'Гамбия' },
    capital: { en: 'Banjul', ru: 'Банжул' },
  },
  {
    code: 'ge',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Georgia', ru: 'Грузия' },
    capital: { en: 'Tbilisi', ru: 'Тбилиси' },
  },
  {
    code: 'de',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Germany', ru: 'Германия' },
    capital: { en: 'Berlin', ru: 'Берлин' },
  },
  {
    code: 'gh',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Ghana', ru: 'Гана' },
    capital: { en: 'Accra', ru: 'Аккра' },
  },
  {
    code: 'gr',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Greece', ru: 'Греция' },
    capital: { en: 'Athens', ru: 'Афины' },
  },
  {
    code: 'gd',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Grenada', ru: 'Гренада' },
    capital: { en: "St. George's", ru: 'Сент-Джорджес' },
  },
  {
    code: 'gt',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'Guatemala', ru: 'Гватемала' },
    capital: { en: 'Guatemala City', ru: 'Гватемала' },
    capitalAliases: { en: ['Guatemala'] },
  },
  {
    code: 'gn',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Guinea', ru: 'Гвинея' },
    capital: { en: 'Conakry', ru: 'Конакри' },
  },
  {
    code: 'gw',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Guinea-Bissau', ru: 'Гвинея-Бисау' },
    capital: { en: 'Bissau', ru: 'Бисау' },
  },
  {
    code: 'gy',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Guyana', ru: 'Гайана' },
    capital: { en: 'Georgetown', ru: 'Джорджтаун' },
  },
  {
    code: 'ht',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Haiti', ru: 'Гаити' },
    capital: { en: 'Port-au-Prince', ru: 'Порт-о-Пренс' },
  },
  {
    code: 'hn',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'Honduras', ru: 'Гондурас' },
    capital: { en: 'Tegucigalpa', ru: 'Тегусигальпа' },
  },
  {
    code: 'hu',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Hungary', ru: 'Венгрия' },
    capital: { en: 'Budapest', ru: 'Будапешт' },
  },
  {
    code: 'is',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Iceland', ru: 'Исландия' },
    capital: { en: 'Reykjavík', ru: 'Рейкьявик' },
  },
  {
    code: 'in',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'India', ru: 'Индия' },
    capital: { en: 'New Delhi', ru: 'Нью-Дели' },
    capitalAliases: { en: ['Delhi'], ru: ['Дели'] },
  },
  // Nusantara is being built as the new capital; Jakarta is still the primary answer.
  {
    code: 'id',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Indonesia', ru: 'Индонезия' },
    capital: { en: 'Jakarta', ru: 'Джакарта' },
    capitalAliases: { en: ['Nusantara'], ru: ['Нусантара'] },
  },
  {
    code: 'ir',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Iran', ru: 'Иран' },
    capital: { en: 'Tehran', ru: 'Тегеран' },
  },
  {
    code: 'iq',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Iraq', ru: 'Ирак' },
    capital: { en: 'Baghdad', ru: 'Багдад' },
  },
  {
    code: 'ie',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Ireland', ru: 'Ирландия' },
    capital: { en: 'Dublin', ru: 'Дублин' },
  },
  // Jerusalem is the capital proclaimed by Israel; its status is disputed internationally.
  {
    code: 'il',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Israel', ru: 'Израиль' },
    capital: { en: 'Jerusalem', ru: 'Иерусалим' },
  },
  {
    code: 'it',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Italy', ru: 'Италия' },
    capital: { en: 'Rome', ru: 'Рим' },
  },
  {
    code: 'jm',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Jamaica', ru: 'Ямайка' },
    capital: { en: 'Kingston', ru: 'Кингстон' },
  },
  {
    code: 'jp',
    region: 'asia',
    subregion: 'eastern-asia',
    name: { en: 'Japan', ru: 'Япония' },
    capital: { en: 'Tokyo', ru: 'Токио' },
  },
  {
    code: 'jo',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Jordan', ru: 'Иордания' },
    capital: { en: 'Amman', ru: 'Амман' },
  },
  {
    code: 'kz',
    region: 'asia',
    subregion: 'central-asia',
    name: { en: 'Kazakhstan', ru: 'Казахстан' },
    capital: { en: 'Astana', ru: 'Астана' },
  },
  {
    code: 'ke',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Kenya', ru: 'Кения' },
    capital: { en: 'Nairobi', ru: 'Найроби' },
  },
  {
    code: 'ki',
    region: 'oceania',
    subregion: 'micronesia',
    name: { en: 'Kiribati', ru: 'Кирибати' },
    capital: { en: 'South Tarawa', ru: 'Южная Тарава' },
    capitalAliases: { en: ['Tarawa'], ru: ['Тарава'] },
  },
  {
    code: 'kw',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Kuwait', ru: 'Кувейт' },
    capital: { en: 'Kuwait City', ru: 'Эль-Кувейт' },
    capitalAliases: { en: ['Kuwait'], ru: ['Кувейт'] },
  },
  {
    code: 'kg',
    region: 'asia',
    subregion: 'central-asia',
    name: { en: 'Kyrgyzstan', ru: 'Кыргызстан' },
    nameAliases: { ru: ['Киргизия'] },
    capital: { en: 'Bishkek', ru: 'Бишкек' },
  },
  {
    code: 'la',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Laos', ru: 'Лаос' },
    capital: { en: 'Vientiane', ru: 'Вьентьян' },
  },
  {
    code: 'lv',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Latvia', ru: 'Латвия' },
    capital: { en: 'Riga', ru: 'Рига' },
  },
  {
    code: 'lb',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Lebanon', ru: 'Ливан' },
    capital: { en: 'Beirut', ru: 'Бейрут' },
  },
  {
    code: 'ls',
    region: 'africa',
    subregion: 'southern-africa',
    name: { en: 'Lesotho', ru: 'Лесото' },
    capital: { en: 'Maseru', ru: 'Масеру' },
  },
  {
    code: 'lr',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Liberia', ru: 'Либерия' },
    capital: { en: 'Monrovia', ru: 'Монровия' },
  },
  {
    code: 'ly',
    region: 'africa',
    subregion: 'northern-africa',
    name: { en: 'Libya', ru: 'Ливия' },
    capital: { en: 'Tripoli', ru: 'Триполи' },
  },
  {
    code: 'li',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Liechtenstein', ru: 'Лихтенштейн' },
    capital: { en: 'Vaduz', ru: 'Вадуц' },
  },
  {
    code: 'lt',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Lithuania', ru: 'Литва' },
    capital: { en: 'Vilnius', ru: 'Вильнюс' },
  },
  {
    code: 'lu',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Luxembourg', ru: 'Люксембург' },
    capital: { en: 'Luxembourg', ru: 'Люксембург' },
  },
  {
    code: 'mg',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Madagascar', ru: 'Мадагаскар' },
    capital: { en: 'Antananarivo', ru: 'Антананариву' },
  },
  {
    code: 'mw',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Malawi', ru: 'Малави' },
    capital: { en: 'Lilongwe', ru: 'Лилонгве' },
  },
  // Kuala Lumpur is the official capital; Putrajaya is the administrative centre.
  {
    code: 'my',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Malaysia', ru: 'Малайзия' },
    capital: { en: 'Kuala Lumpur', ru: 'Куала-Лумпур' },
    capitalAliases: { en: ['Putrajaya'], ru: ['Путраджая'] },
  },
  {
    code: 'mv',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Maldives', ru: 'Мальдивы' },
    capital: { en: 'Malé', ru: 'Мале' },
  },
  {
    code: 'ml',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Mali', ru: 'Мали' },
    capital: { en: 'Bamako', ru: 'Бамако' },
  },
  {
    code: 'mt',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Malta', ru: 'Мальта' },
    capital: { en: 'Valletta', ru: 'Валлетта' },
  },
  {
    code: 'mh',
    region: 'oceania',
    subregion: 'micronesia',
    name: { en: 'Marshall Islands', ru: 'Маршалловы Острова' },
    capital: { en: 'Majuro', ru: 'Маджуро' },
  },
  {
    code: 'mr',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Mauritania', ru: 'Мавритания' },
    capital: { en: 'Nouakchott', ru: 'Нуакшот' },
  },
  {
    code: 'mu',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Mauritius', ru: 'Маврикий' },
    capital: { en: 'Port Louis', ru: 'Порт-Луи' },
  },
  {
    code: 'mx',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'Mexico', ru: 'Мексика' },
    capital: { en: 'Mexico City', ru: 'Мехико' },
  },
  {
    code: 'fm',
    region: 'oceania',
    subregion: 'micronesia',
    name: { en: 'Micronesia', ru: 'Микронезия' },
    nameAliases: {
      en: ['Federated States of Micronesia'],
      ru: ['Федеративные Штаты Микронезии'],
    },
    capital: { en: 'Palikir', ru: 'Паликир' },
  },
  {
    code: 'md',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Moldova', ru: 'Молдова' },
    nameAliases: { ru: ['Молдавия'] },
    capital: { en: 'Chișinău', ru: 'Кишинёв' },
    capitalAliases: { en: ['Kishinev'] },
  },
  {
    code: 'mc',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Monaco', ru: 'Монако' },
    capital: { en: 'Monaco', ru: 'Монако' },
  },
  {
    code: 'mn',
    region: 'asia',
    subregion: 'eastern-asia',
    name: { en: 'Mongolia', ru: 'Монголия' },
    capital: { en: 'Ulaanbaatar', ru: 'Улан-Батор' },
    capitalAliases: { en: ['Ulan Bator'] },
  },
  {
    code: 'me',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Montenegro', ru: 'Черногория' },
    capital: { en: 'Podgorica', ru: 'Подгорица' },
  },
  {
    code: 'ma',
    region: 'africa',
    subregion: 'northern-africa',
    name: { en: 'Morocco', ru: 'Марокко' },
    capital: { en: 'Rabat', ru: 'Рабат' },
  },
  {
    code: 'mz',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Mozambique', ru: 'Мозамбик' },
    capital: { en: 'Maputo', ru: 'Мапуту' },
  },
  {
    code: 'mm',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Myanmar', ru: 'Мьянма' },
    nameAliases: { en: ['Burma'], ru: ['Бирма'] },
    capital: { en: 'Naypyidaw', ru: 'Нейпьидо' },
    capitalAliases: { en: ['Nay Pyi Taw'] },
  },
  {
    code: 'na',
    region: 'africa',
    subregion: 'southern-africa',
    name: { en: 'Namibia', ru: 'Намибия' },
    capital: { en: 'Windhoek', ru: 'Виндхук' },
  },
  // Nauru has no official capital; Yaren District hosts the government.
  {
    code: 'nr',
    region: 'oceania',
    subregion: 'micronesia',
    name: { en: 'Nauru', ru: 'Науру' },
    capital: { en: 'Yaren', ru: 'Ярен' },
    capitalAliases: { en: ['Yaren District'] },
  },
  {
    code: 'np',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Nepal', ru: 'Непал' },
    capital: { en: 'Kathmandu', ru: 'Катманду' },
  },
  {
    code: 'nl',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Netherlands', ru: 'Нидерланды' },
    nameAliases: {
      en: ['Holland', 'Kingdom of the Netherlands'],
      ru: ['Голландия', 'Королевство Нидерландов'],
    },
    capital: { en: 'Amsterdam', ru: 'Амстердам' },
  },
  {
    code: 'nz',
    region: 'oceania',
    subregion: 'australia-and-new-zealand',
    name: { en: 'New Zealand', ru: 'Новая Зеландия' },
    capital: { en: 'Wellington', ru: 'Веллингтон' },
  },
  {
    code: 'ni',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'Nicaragua', ru: 'Никарагуа' },
    capital: { en: 'Managua', ru: 'Манагуа' },
  },
  {
    code: 'ne',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Niger', ru: 'Нигер' },
    capital: { en: 'Niamey', ru: 'Ниамей' },
  },
  {
    code: 'ng',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Nigeria', ru: 'Нигерия' },
    capital: { en: 'Abuja', ru: 'Абуджа' },
  },
  {
    code: 'kp',
    region: 'asia',
    subregion: 'eastern-asia',
    name: { en: 'North Korea', ru: 'Северная Корея' },
    nameAliases: {
      en: ["Democratic People's Republic of Korea", 'DPRK'],
      ru: ['КНДР'],
    },
    capital: { en: 'Pyongyang', ru: 'Пхеньян' },
  },
  {
    code: 'mk',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'North Macedonia', ru: 'Северная Македония' },
    nameAliases: { en: ['Macedonia'], ru: ['Македония'] },
    capital: { en: 'Skopje', ru: 'Скопье' },
  },
  {
    code: 'no',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Norway', ru: 'Норвегия' },
    capital: { en: 'Oslo', ru: 'Осло' },
  },
  {
    code: 'om',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Oman', ru: 'Оман' },
    capital: { en: 'Muscat', ru: 'Маскат' },
  },
  {
    code: 'pk',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Pakistan', ru: 'Пакистан' },
    capital: { en: 'Islamabad', ru: 'Исламабад' },
  },
  {
    code: 'pw',
    region: 'oceania',
    subregion: 'micronesia',
    name: { en: 'Palau', ru: 'Палау' },
    capital: { en: 'Ngerulmud', ru: 'Нгерулмуд' },
  },
  // East Jerusalem is the proclaimed capital; Ramallah is the administrative seat of government.
  {
    code: 'ps',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Palestine', ru: 'Палестина' },
    nameAliases: { en: ['State of Palestine'], ru: ['Государство Палестина'] },
    capital: { en: 'Ramallah', ru: 'Рамалла' },
    capitalAliases: { en: ['East Jerusalem'], ru: ['Восточный Иерусалим'] },
  },
  {
    code: 'pa',
    region: 'north-america',
    subregion: 'central-america',
    name: { en: 'Panama', ru: 'Панама' },
    capital: { en: 'Panama City', ru: 'Панама' },
    capitalAliases: { en: ['Panama'] },
  },
  {
    code: 'pg',
    region: 'oceania',
    subregion: 'melanesia',
    name: { en: 'Papua New Guinea', ru: 'Папуа — Новая Гвинея' },
    capital: { en: 'Port Moresby', ru: 'Порт-Морсби' },
  },
  {
    code: 'py',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Paraguay', ru: 'Парагвай' },
    capital: { en: 'Asunción', ru: 'Асунсьон' },
  },
  {
    code: 'pe',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Peru', ru: 'Перу' },
    capital: { en: 'Lima', ru: 'Лима' },
  },
  {
    code: 'ph',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Philippines', ru: 'Филиппины' },
    capital: { en: 'Manila', ru: 'Манила' },
  },
  {
    code: 'pl',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Poland', ru: 'Польша' },
    capital: { en: 'Warsaw', ru: 'Варшава' },
  },
  {
    code: 'pt',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Portugal', ru: 'Португалия' },
    capital: { en: 'Lisbon', ru: 'Лиссабон' },
  },
  {
    code: 'qa',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Qatar', ru: 'Катар' },
    capital: { en: 'Doha', ru: 'Доха' },
  },
  {
    code: 'cg',
    region: 'africa',
    subregion: 'middle-africa',
    name: { en: 'Republic of the Congo', ru: 'Республика Конго' },
    nameAliases: {
      en: ['Congo', 'Congo-Brazzaville'],
      ru: ['Конго', 'Конго-Браззавиль'],
    },
    capital: { en: 'Brazzaville', ru: 'Браззавиль' },
  },
  {
    code: 'ro',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Romania', ru: 'Румыния' },
    capital: { en: 'Bucharest', ru: 'Бухарест' },
  },
  {
    code: 'ru',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Russia', ru: 'Россия' },
    nameAliases: { en: ['Russian Federation'], ru: ['Российская Федерация'] },
    capital: { en: 'Moscow', ru: 'Москва' },
  },
  {
    code: 'rw',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Rwanda', ru: 'Руанда' },
    capital: { en: 'Kigali', ru: 'Кигали' },
  },
  {
    code: 'kn',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Saint Kitts and Nevis', ru: 'Сент-Китс и Невис' },
    capital: { en: 'Basseterre', ru: 'Бастер' },
  },
  {
    code: 'lc',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Saint Lucia', ru: 'Сент-Люсия' },
    capital: { en: 'Castries', ru: 'Кастри' },
  },
  {
    code: 'vc',
    region: 'north-america',
    subregion: 'caribbean',
    name: {
      en: 'Saint Vincent and the Grenadines',
      ru: 'Сент-Винсент и Гренадины',
    },
    capital: { en: 'Kingstown', ru: 'Кингстаун' },
  },
  {
    code: 'ws',
    region: 'oceania',
    subregion: 'polynesia',
    name: { en: 'Samoa', ru: 'Самоа' },
    capital: { en: 'Apia', ru: 'Апиа' },
  },
  {
    code: 'sm',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'San Marino', ru: 'Сан-Марино' },
    capital: { en: 'San Marino', ru: 'Сан-Марино' },
  },
  {
    code: 'st',
    region: 'africa',
    subregion: 'middle-africa',
    name: { en: 'São Tomé and Príncipe', ru: 'Сан-Томе и Принсипи' },
    capital: { en: 'São Tomé', ru: 'Сан-Томе' },
  },
  {
    code: 'sa',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Saudi Arabia', ru: 'Саудовская Аравия' },
    capital: { en: 'Riyadh', ru: 'Эр-Рияд' },
  },
  {
    code: 'sn',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Senegal', ru: 'Сенегал' },
    capital: { en: 'Dakar', ru: 'Дакар' },
  },
  {
    code: 'rs',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Serbia', ru: 'Сербия' },
    capital: { en: 'Belgrade', ru: 'Белград' },
  },
  {
    code: 'sc',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Seychelles', ru: 'Сейшельские Острова' },
    nameAliases: { ru: ['Сейшелы'] },
    capital: { en: 'Victoria', ru: 'Виктория' },
  },
  {
    code: 'sl',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Sierra Leone', ru: 'Сьерра-Леоне' },
    capital: { en: 'Freetown', ru: 'Фритаун' },
  },
  {
    code: 'sg',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Singapore', ru: 'Сингапур' },
    capital: { en: 'Singapore', ru: 'Сингапур' },
  },
  {
    code: 'sk',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Slovakia', ru: 'Словакия' },
    capital: { en: 'Bratislava', ru: 'Братислава' },
  },
  {
    code: 'si',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Slovenia', ru: 'Словения' },
    capital: { en: 'Ljubljana', ru: 'Любляна' },
  },
  {
    code: 'sb',
    region: 'oceania',
    subregion: 'melanesia',
    name: { en: 'Solomon Islands', ru: 'Соломоновы Острова' },
    capital: { en: 'Honiara', ru: 'Хониара' },
  },
  {
    code: 'so',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Somalia', ru: 'Сомали' },
    capital: { en: 'Mogadishu', ru: 'Могадишо' },
  },
  // Pretoria (executive) is the primary answer; Cape Town (legislative) and Bloemfontein (judicial) are also accepted.
  {
    code: 'za',
    region: 'africa',
    subregion: 'southern-africa',
    name: { en: 'South Africa', ru: 'ЮАР' },
    nameAliases: { ru: ['Южно-Африканская Республика', 'Южная Африка'] },
    capital: { en: 'Pretoria', ru: 'Претория' },
    capitalAliases: {
      en: ['Cape Town', 'Bloemfontein'],
      ru: ['Кейптаун', 'Блумфонтейн'],
    },
  },
  {
    code: 'kr',
    region: 'asia',
    subregion: 'eastern-asia',
    name: { en: 'South Korea', ru: 'Южная Корея' },
    nameAliases: { en: ['Republic of Korea'], ru: ['Республика Корея'] },
    capital: { en: 'Seoul', ru: 'Сеул' },
  },
  {
    code: 'ss',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'South Sudan', ru: 'Южный Судан' },
    capital: { en: 'Juba', ru: 'Джуба' },
  },
  {
    code: 'es',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Spain', ru: 'Испания' },
    capital: { en: 'Madrid', ru: 'Мадрид' },
  },
  // Sri Jayawardenepura Kotte is the legislative capital; Colombo is the executive and commercial capital.
  {
    code: 'lk',
    region: 'asia',
    subregion: 'southern-asia',
    name: { en: 'Sri Lanka', ru: 'Шри-Ланка' },
    capital: {
      en: 'Sri Jayawardenepura Kotte',
      ru: 'Шри-Джаяварденепура-Котте',
    },
    capitalAliases: { en: ['Kotte', 'Colombo'], ru: ['Котте', 'Коломбо'] },
  },
  {
    code: 'sd',
    region: 'africa',
    subregion: 'northern-africa',
    name: { en: 'Sudan', ru: 'Судан' },
    capital: { en: 'Khartoum', ru: 'Хартум' },
  },
  {
    code: 'sr',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Suriname', ru: 'Суринам' },
    capital: { en: 'Paramaribo', ru: 'Парамарибо' },
  },
  {
    code: 'se',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'Sweden', ru: 'Швеция' },
    capital: { en: 'Stockholm', ru: 'Стокгольм' },
  },
  {
    code: 'ch',
    region: 'europe',
    subregion: 'western-europe',
    name: { en: 'Switzerland', ru: 'Швейцария' },
    capital: { en: 'Bern', ru: 'Берн' },
    capitalAliases: { en: ['Berne'] },
  },
  {
    code: 'sy',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Syria', ru: 'Сирия' },
    capital: { en: 'Damascus', ru: 'Дамаск' },
  },
  {
    code: 'tj',
    region: 'asia',
    subregion: 'central-asia',
    name: { en: 'Tajikistan', ru: 'Таджикистан' },
    capital: { en: 'Dushanbe', ru: 'Душанбе' },
  },
  {
    code: 'tz',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Tanzania', ru: 'Танзания' },
    capital: { en: 'Dodoma', ru: 'Додома' },
  },
  {
    code: 'th',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Thailand', ru: 'Таиланд' },
    capital: { en: 'Bangkok', ru: 'Бангкок' },
  },
  {
    code: 'tl',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Timor-Leste', ru: 'Восточный Тимор' },
    nameAliases: { en: ['East Timor'], ru: ['Тимор-Лешти'] },
    capital: { en: 'Dili', ru: 'Дили' },
  },
  {
    code: 'tg',
    region: 'africa',
    subregion: 'western-africa',
    name: { en: 'Togo', ru: 'Того' },
    capital: { en: 'Lomé', ru: 'Ломе' },
  },
  {
    code: 'to',
    region: 'oceania',
    subregion: 'polynesia',
    name: { en: 'Tonga', ru: 'Тонга' },
    capital: { en: 'Nukuʻalofa', ru: 'Нукуалофа' },
  },
  {
    code: 'tt',
    region: 'north-america',
    subregion: 'caribbean',
    name: { en: 'Trinidad and Tobago', ru: 'Тринидад и Тобаго' },
    capital: { en: 'Port of Spain', ru: 'Порт-оф-Спейн' },
  },
  {
    code: 'tn',
    region: 'africa',
    subregion: 'northern-africa',
    name: { en: 'Tunisia', ru: 'Тунис' },
    capital: { en: 'Tunis', ru: 'Тунис' },
  },
  {
    code: 'tr',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Turkey', ru: 'Турция' },
    nameAliases: { en: ['Türkiye'] },
    capital: { en: 'Ankara', ru: 'Анкара' },
  },
  {
    code: 'tm',
    region: 'asia',
    subregion: 'central-asia',
    name: { en: 'Turkmenistan', ru: 'Туркменистан' },
    capital: { en: 'Ashgabat', ru: 'Ашхабад' },
  },
  {
    code: 'tv',
    region: 'oceania',
    subregion: 'polynesia',
    name: { en: 'Tuvalu', ru: 'Тувалу' },
    capital: { en: 'Funafuti', ru: 'Фунафути' },
  },
  {
    code: 'ug',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Uganda', ru: 'Уганда' },
    capital: { en: 'Kampala', ru: 'Кампала' },
  },
  {
    code: 'ua',
    region: 'europe',
    subregion: 'eastern-europe',
    name: { en: 'Ukraine', ru: 'Украина' },
    capital: { en: 'Kyiv', ru: 'Киев' },
    capitalAliases: { en: ['Kiev'] },
  },
  {
    code: 'ae',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'United Arab Emirates', ru: 'Объединённые Арабские Эмираты' },
    nameAliases: { en: ['UAE'], ru: ['ОАЭ'] },
    capital: { en: 'Abu Dhabi', ru: 'Абу-Даби' },
  },
  {
    code: 'gb',
    region: 'europe',
    subregion: 'northern-europe',
    name: { en: 'United Kingdom', ru: 'Великобритания' },
    nameAliases: {
      en: ['UK', 'Great Britain', 'Britain'],
      ru: ['Соединённое Королевство', 'Британия'],
    },
    capital: { en: 'London', ru: 'Лондон' },
  },
  {
    code: 'us',
    region: 'north-america',
    subregion: 'northern-america',
    name: { en: 'United States', ru: 'США' },
    nameAliases: {
      en: ['United States of America', 'USA', 'US', 'America'],
      ru: ['Соединённые Штаты Америки', 'Соединённые Штаты', 'Америка'],
    },
    capital: { en: 'Washington, D.C.', ru: 'Вашингтон' },
    capitalAliases: { en: ['Washington'] },
  },
  {
    code: 'uy',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Uruguay', ru: 'Уругвай' },
    capital: { en: 'Montevideo', ru: 'Монтевидео' },
  },
  {
    code: 'uz',
    region: 'asia',
    subregion: 'central-asia',
    name: { en: 'Uzbekistan', ru: 'Узбекистан' },
    capital: { en: 'Tashkent', ru: 'Ташкент' },
  },
  {
    code: 'vu',
    region: 'oceania',
    subregion: 'melanesia',
    name: { en: 'Vanuatu', ru: 'Вануату' },
    capital: { en: 'Port Vila', ru: 'Порт-Вила' },
  },
  {
    code: 'va',
    region: 'europe',
    subregion: 'southern-europe',
    name: { en: 'Vatican City', ru: 'Ватикан' },
    nameAliases: { en: ['Vatican', 'Holy See'], ru: ['Святой Престол'] },
    capital: { en: 'Vatican City', ru: 'Ватикан' },
  },
  {
    code: 've',
    region: 'south-america',
    subregion: 'south-america',
    name: { en: 'Venezuela', ru: 'Венесуэла' },
    capital: { en: 'Caracas', ru: 'Каракас' },
  },
  {
    code: 'vn',
    region: 'asia',
    subregion: 'south-eastern-asia',
    name: { en: 'Vietnam', ru: 'Вьетнам' },
    nameAliases: { en: ['Viet Nam'] },
    capital: { en: 'Hanoi', ru: 'Ханой' },
  },
  // Sanaa is the constitutional capital; Aden has served as the temporary capital.
  {
    code: 'ye',
    region: 'asia',
    subregion: 'western-asia',
    name: { en: 'Yemen', ru: 'Йемен' },
    capital: { en: 'Sanaa', ru: 'Сана' },
    capitalAliases: { en: ['Aden'], ru: ['Аден'] },
  },
  {
    code: 'zm',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Zambia', ru: 'Замбия' },
    capital: { en: 'Lusaka', ru: 'Лусака' },
  },
  {
    code: 'zw',
    region: 'africa',
    subregion: 'eastern-africa',
    name: { en: 'Zimbabwe', ru: 'Зимбабве' },
    capital: { en: 'Harare', ru: 'Хараре' },
  },
];
