import {
  DIFFICULTIES,
  QUIZ_CATEGORIES,
  QUIZ_MODES,
  QUIZ_SCOPES,
} from '@world-quiz/quiz/domain';
import { z } from 'zod';
import { countryCodeSchema, epochMillisSchema, uuidSchema } from './common';
import { challengeOutcomeSchema } from './leaderboard';

/**
 * Upper bound for answers in one session. Fixed and challenge sessions are at
 * most 195 questions; Endless is unbounded in the domain, so the API caps what
 * it accepts in one request.
 */
export const MAX_SUBMISSIONS_PER_SESSION = 1000;

/** Longest accepted typed answer; real names are far shorter. */
export const MAX_TYPED_ANSWER_LENGTH = 100;

export const submittedAnswerSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('choice'), countryCode: countryCodeSchema }),
  z.object({
    kind: z.literal('text'),
    text: z.string().max(MAX_TYPED_ANSWER_LENGTH),
  }),
]);

export const quizConfigSchema = z.strictObject({
  category: z.enum(QUIZ_CATEGORIES),
  difficulty: z.enum(DIFFICULTIES),
  mode: z.enum(QUIZ_MODES),
  scope: z.enum(QUIZ_SCOPES),
  questionCount: z.int().min(1).max(MAX_SUBMISSIONS_PER_SESSION).optional(),
  countryCodes: z
    .array(countryCodeSchema)
    .min(1)
    .max(195)
    .readonly()
    .optional(),
});

/**
 * `POST /v1/sessions`: a finished quiz session as the client played it.
 *
 * It carries only what the player did — configuration, seed, timestamps and
 * the answers given. Score, correctness and mastery are never sent: the server
 * replays the session with the quiz domain and grades every answer itself.
 * `id` is generated by the client once per session and makes the request
 * idempotent, so a retry after a lost response cannot record it twice.
 */
export const submitSessionRequestSchema = z.strictObject({
  id: uuidSchema,
  config: quizConfigSchema,
  seed: z.string().min(1).max(100),
  startedAt: epochMillisSchema,
  finishedAt: epochMillisSchema,
  endReason: z.enum(['completed', 'stopped', 'time-up']),
  submissions: z
    .array(
      z.strictObject({
        answer: submittedAnswerSchema,
        answeredAt: epochMillisSchema,
      }),
    )
    .max(MAX_SUBMISSIONS_PER_SESSION),
  /**
   * Challenge sessions only: the challenge issued by `POST /v1/challenges`
   * whose seed this session was played with. Optional without a default, so
   * the request hash of sessions that do not carry it is unchanged.
   */
  challengeId: uuidSchema.optional(),
});

export type SubmitSessionRequest = z.infer<typeof submitSessionRequestSchema>;

/** The server's own grading of a recorded session. */
export const sessionResultSchema = z.object({
  id: uuidSchema,
  config: quizConfigSchema,
  summary: z.object({
    answered: z.int(),
    correct: z.int(),
    incorrect: z.int(),
    accuracy: z.number(),
    durationMs: z.int(),
    endReason: z.enum(['completed', 'stopped', 'time-up']),
    completed: z.boolean(),
    perfect: z.boolean(),
  }),
  /** When the server stored the session (ISO 8601). */
  recordedAt: z.iso.datetime(),
  /** Challenge sessions only: whether the run is ranked, and where. */
  challenge: challengeOutcomeSchema.optional(),
});

export type SessionResult = z.infer<typeof sessionResultSchema>;

/** Largest page of `GET /v1/sessions`; the default is `DEFAULT_HISTORY_PAGE_SIZE`. */
export const MAX_HISTORY_PAGE_SIZE = 100;
export const DEFAULT_HISTORY_PAGE_SIZE = 50;

/**
 * `GET /v1/sessions?after=&limit=`: the query of the player's history.
 *
 * `after` is the `cursor` of a previous page, opaque to clients. Unknown
 * parameters are rejected, like unknown body fields.
 */
export const sessionHistoryQuerySchema = z.strictObject({
  after: z
    .string()
    .regex(/^[\w-]{1,200}$/)
    .optional(),
  limit: z.coerce
    .number()
    .int()
    .min(1)
    .max(MAX_HISTORY_PAGE_SIZE)
    .default(DEFAULT_HISTORY_PAGE_SIZE),
});

export type SessionHistoryQuery = z.infer<typeof sessionHistoryQuerySchema>;

/**
 * One recorded session with the server's grading of every answer, in the
 * order they were given. Enough to rebuild learning progress on another
 * device: each answer becomes a progress event (category and difficulty come
 * from `config`, the position in `answers` is the sequence).
 */
export const sessionHistoryEntrySchema = sessionResultSchema.extend({
  startedAt: epochMillisSchema,
  finishedAt: epochMillisSchema,
  answers: z
    .array(
      z.object({
        countryCode: countryCodeSchema,
        correct: z.boolean(),
        answeredAt: epochMillisSchema,
      }),
    )
    .readonly(),
});

export type SessionHistoryEntry = z.infer<typeof sessionHistoryEntrySchema>;

/**
 * A page of history, oldest recorded first.
 *
 * `cursor` marks the end of this page: pass it as `after` for the next page
 * now (`hasMore`) or for sessions recorded later (a sync keeps the last one).
 * It is `null` only when there has never been a session to return.
 */
export const sessionHistoryPageSchema = z.object({
  sessions: z.array(sessionHistoryEntrySchema),
  cursor: z.string().nullable(),
  hasMore: z.boolean(),
});

export type SessionHistoryPage = z.infer<typeof sessionHistoryPageSchema>;
