import {
  DIFFICULTIES,
  QUIZ_CATEGORIES,
  QUIZ_MODES,
  QUIZ_SCOPES,
} from '@world-quiz/quiz/domain';
import { z } from 'zod';
import { countryCodeSchema, epochMillisSchema, uuidSchema } from './common';

/**
 * Upper bound for answers in one session. Fixed and challenge sessions are at
 * most 195 questions; Endless is unbounded in the domain, so the API caps what
 * it accepts in one request.
 */
export const MAX_SUBMISSIONS_PER_SESSION = 1000;

/** Longest accepted typed answer; real names are far shorter. */
export const MAX_TYPED_ANSWER_LENGTH = 100;

export const submittedAnswerSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('choice'), countryCode: countryCodeSchema }),
  z.object({
    kind: z.literal('text'),
    text: z.string().max(MAX_TYPED_ANSWER_LENGTH),
  }),
]);

export const quizConfigSchema = z.strictObject({
  category: z.enum(QUIZ_CATEGORIES),
  difficulty: z.enum(DIFFICULTIES),
  mode: z.enum(QUIZ_MODES),
  scope: z.enum(QUIZ_SCOPES),
  questionCount: z.int().min(1).max(MAX_SUBMISSIONS_PER_SESSION).optional(),
  countryCodes: z
    .array(countryCodeSchema)
    .min(1)
    .max(195)
    .readonly()
    .optional(),
});

/**
 * `POST /v1/sessions`: a finished quiz session as the client played it.
 *
 * It carries only what the player did — configuration, seed, timestamps and
 * the answers given. Score, correctness and mastery are never sent: the server
 * replays the session with the quiz domain and grades every answer itself.
 * `id` is generated by the client once per session and makes the request
 * idempotent, so a retry after a lost response cannot record it twice.
 */
export const submitSessionRequestSchema = z.strictObject({
  id: uuidSchema,
  config: quizConfigSchema,
  seed: z.string().min(1).max(100),
  startedAt: epochMillisSchema,
  finishedAt: epochMillisSchema,
  endReason: z.enum(['completed', 'stopped', 'time-up']),
  submissions: z
    .array(
      z.strictObject({
        answer: submittedAnswerSchema,
        answeredAt: epochMillisSchema,
      }),
    )
    .max(MAX_SUBMISSIONS_PER_SESSION),
});

export type SubmitSessionRequest = z.infer<typeof submitSessionRequestSchema>;

/** The server's own grading of a recorded session. */
export const sessionResultSchema = z.object({
  id: uuidSchema,
  config: quizConfigSchema,
  summary: z.object({
    answered: z.int(),
    correct: z.int(),
    incorrect: z.int(),
    accuracy: z.number(),
    durationMs: z.int(),
    endReason: z.enum(['completed', 'stopped', 'time-up']),
    completed: z.boolean(),
    perfect: z.boolean(),
  }),
  /** When the server stored the session (ISO 8601). */
  recordedAt: z.iso.datetime(),
});

export type SessionResult = z.infer<typeof sessionResultSchema>;
